spring:
  datasource:
    validation-query: SELECT 1
    validation-query-timeout: 5000
    test-on-borrow: true
    test-on-connect: true
    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/fly?characterEncoding=utf-8&useSSL=false
    username: root
    password: root123
    url: jdbc:mysql://127.0.0.1:3306/projectFlowDemo?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect



